---

- name: A playbook that creates a charon cluster
  hosts: all
  gather_facts: false
  become: true

  pre_tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_valid
      ignore_errors: true
      changed_when: docker_valid != 0

  roles:
    - docker_install
    - charon_cluster
