---

- name: A playbook that creates a charon node
  hosts: all
  gather_facts: false
  become: true

  pre_tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_valid
      ignore_errors: true
      changed_when: docker_valid != 0

  roles:
    - name: Install Docker
      when: docker_valid.failed
      role: docker_install
    - name: Setup and run charon-node
      role: charon_node
