- name: Find charon folders
  find:
    paths: /Users/lukehackett/Documents/Obol/obol-ansible/.charon/cluster
    file_type: directory
    recurse: false
    patterns: 'node*'
  register: node_folders

- name: Loop through cluster folders
  ansible.builtin.include_role:
    name: charon-node
  vars:
    nodeIndex: '{{ item.0 }}'
    config:
      lockFile: '{{ item.1.path }}/cluster-lock.json'
      privateKeyFile: '{{ item.1.path }}/charon-enr-private-key'
      validatorKeysDir: '{{ item.1.path }}/validator_keys/'
  with_indexed_items: '{{ node_folders.files }}'
