- name: Find charon folders
  find:
    paths: ./.charon/cluster
    file_type: directory
    recurse: false
    patterns: 'node*'
  delegate_to: localhost
  register: node_folders

- name: Loop through cluster folders
  ansible.builtin.include_role:
    name: charon-node
  vars:
    node_index: '{{ item.0 }}'
    node_config:
      lock_file: '{{ item.1.path }}/cluster-lock.json'
      private_key_file: '{{ item.1.path }}/charon-enr-private-key'
      validator_keys_dir: '{{ item.1.path }}/validator_keys/'
  with_indexed_items: '{{ node_folders.files }}'
