name: ansible-lint
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Run ansible-lint
        uses: ansible/ansible-lint@5fac056c45595896c973fbde871f01f6cb14d74c # v26
